#!/usr/bin/ruby
def help
  puts "USAGE: color -p PATTERN [-s SAVE_FILE] [-i File] STDIN"
  puts "  -i : File input. This option always last."
  puts "  -I : Input file list."
  puts "  -p : you can use regular expression. you don't need '/'"
end

pattern = ARGV[ARGV.index('-p') + 1] if ARGV.include?('-p')
help if ARGV.include?('-h') || ARGV.include?('--help')

if ARGV.include?('-h')
  help
  exit(1)
end
if pattern == nil && (infile == [] || standerd == nil ) 
  help
  exit(1)
end

infile = Array.new
input = ''
if ARGV.include?('-i') 
  while ARGV[ARGV.index('-i') + 1] != nil  do
    infile.push(ARGV.pop)
  end
elsif ARGV.include?('-I')
  File.open(ARGV[ARGV.index('-I') + 1]).each_line do |line|
    infile.push(line.chomp)
  end
else
  while ARGV != [] do ARGV.shift end
  input = ARGF.read
end

if infile != [] 
  infile.each do |file|
    File.open(file, "r").each_line do |line|
      input << line
    end
  end
end

domhash = Hash.new
st = ""; i = 0; im = 0
input.each_line do |line|
  line.chomp.scan(/#{pattern}/).each do |dom|
    i += 1                if domhash.fetch(dom, nil) == nil
    i += 1                if i == 16 || i == 232 || i == 233 || i == 256 
    domhash.store(dom, i) if domhash.fetch(dom, nil) == nil 
    im = 1 if i > 256
  end
  st << line
end

domhash.each_key do |key|
  st.gsub!(key, "\e[38;05;#{domhash[key]};1m#{key}\e[0m")
end
puts st
